<?php
$form = $this->form;
$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Наименование'
    ]);

$form->get('article')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Колонка артикула',
    ]);

$form->get('iid')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Колонка внутреннего артикула',
    ]);

$form->get('producer')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Колонка производитель',
    ]);

$form->get('country')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Колонка страна',
    ]);

$form->get('title')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Колонка нименование товара',
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Колонка описание товара',
    ]);

$form->get('image')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Колонка картинка товара',
    ]);

$form->get('price')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Колонка цена',
    ]);

$form->get('currency')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Колонка валюта',
    ]);

$form->get('rate')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Колонка курс валюты',
    ]);

$form->get('rest')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Колонка количество',
    ]);

$form->get('unit')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Колонка единица измерения',
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

            
            <?= $this->form()->openTag($form); ?>
            
            <div class="modal-header">
                <h5 class="modal-title">Настройка прайса</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <?= $this->formLabel($form->get('name')); ?>
                            <?= $this->formElement($form->get('name')); ?>
                            <?= $this->formElementErrors($form->get('name')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('article')); ?>
                            <?= $this->formElement($form->get('article')); ?>
                            <?= $this->formElementErrors($form->get('article')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('producer')); ?>
                            <?= $this->formElement($form->get('producer')); ?>
                            <?= $this->formElementErrors($form->get('producer')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('title')); ?>
                            <?= $this->formElement($form->get('title')); ?>
                            <?= $this->formElementErrors($form->get('title')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('image')); ?>
                            <?= $this->formElement($form->get('image')); ?>
                            <?= $this->formElementErrors($form->get('image')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('price')); ?>
                            <?= $this->formElement($form->get('price')); ?>
                            <?= $this->formElementErrors($form->get('price')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('rest')); ?>
                            <?= $this->formElement($form->get('rest')); ?>
                            <?= $this->formElementErrors($form->get('rest')); ?>                  
                        </div>

                    </div>
                    
                    <div class="col-md-5">

                        <div class="form-group">
                            <?= $this->formLabel($form->get('status')); ?>
                            <?= $this->formElement($form->get('status')); ?>
                            <?= $this->formElementErrors($form->get('status')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('iid')); ?>
                            <?= $this->formElement($form->get('iid')); ?>
                            <?= $this->formElementErrors($form->get('iid')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('country')); ?>
                            <?= $this->formElement($form->get('country')); ?>
                            <?= $this->formElementErrors($form->get('country')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('description')); ?>
                            <?= $this->formElement($form->get('description')); ?>
                            <?= $this->formElementErrors($form->get('description')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('currency')); ?>
                            <?= $this->formElement($form->get('currency')); ?>
                            <?= $this->formElementErrors($form->get('currency')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('rate')); ?>
                            <?= $this->formElement($form->get('rate')); ?>
                            <?= $this->formElementErrors($form->get('rate')); ?>                  
                        </div>

                        <div class="form-group">
                            <?= $this->formLabel($form->get('unit')); ?>
                            <?= $this->formElement($form->get('unit')); ?>
                            <?= $this->formElementErrors($form->get('unit')); ?>                  
                        </div>

                    </div>        
                </div>
            </div>    
                
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="form-submit">Сохранить</button>
            </div>
                
            <?= $this->form()->closeTag(); ?>
            
<script>
    $('#form-submit').on('click', function() {
        $.ajax({
            type: 'POST',
            url: '/pricesettings/form/<?= $supplier->getId() ?>?pricesettings=<?= ($pricesettings ? $pricesettings->getId():'') ?>',
            data: $('#pricesettings-form').serialize()
        })
            .done(function (data) {
                if (data == 'ok'){
                    $('#modal-dialog').modal('hide');
                    window.location.reload();
                } else {
                    $('#modal-content').html(data);
                }    
            })
            .fail(function (e) {
                console.log(e);
                alert("Ошибка при открытии формы.");

            });
    })    
</script>