<?php
$this->headTitle('Офис');

$this->mainMenu()->setActiveItemId('offices');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Офисы'=>$this->url('offices'),
            $office->getName()=>$this->url('offices', ['action'=>'view', 'id'=>$office->getId()])
            ]);

$this->headScript()
            ->appendFile($this->basePath('js/jquery.mask.min.js'))
        ;

?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<div class="row">
    <div class="col-sm-9">
        <div id="section1">
            <h2>Офис</h2>
            <p>
                <a class="btn btn-default" href="<?= $this->url('offices', 
                                    ['action'=>'edit', 'id'=>$office->getId()]); ?>">
                                <span class="glyphicon glyphicon-pencil" ></span> Изменить
                </a>
            </p>

            <table class="table table-striped table-bordered">
                 <tr>
                    <th>ID:</th>
                    <td><?= $this->escapeHtml($office->getId()) ?></th>
                </tr>
                 <tr>
                    <th>APL Id:</th>
                    <td><?= $this->escapeHtml($office->getAplId()) ?></th>
                </tr>
                <tr>
                    <th>Наименование:</th>
                    <td><?= $this->escapeHtml($office->getName()) ?></th>
                </tr>
                <tr>
                    <th>Регион:</th>
                    <td><?= $this->escapeHtml($office->getRegion()->getFullName()) ?></th>
                </tr>
                <tr>
                    <th>Статус:</th>
                    <td><?= $this->escapeHtml($office->getStatusAsString()) ?></th>
                </tr>
            </table>
        </div>
        <hr>
        <div id="section2">
            <h2>Контактные телефоны</h2>
            <?php foreach ($office->getContacts() as $contact):?>
                <p>
                    <button value="/contact/phone-form/<?= $contact->getId() ?>" class="btn btn-default"
                            data-toggle="modal" data-target="#modal-dialog" title="Добавить телефон">
                        <span class="glyphicon glyphicon-phone" ></span>
                        Добавить телефон
                    </button>                    
                </p>
                <table class="table table-striped table-bordered">
                    <?php foreach ($contact->getPhones() as $phone): ?>
                        <tr>
                           <th class="phone_name">
                                <div class="pull-left">
                                    <?= $phone->getName()?>
                                    <span><?= $phone->getComment()?></span>
                                </div>
                                <div class="pull-right">
                                    <button value="/contact/phone-form/<?= $contact->getId() ?>?phone=<?= ($phone ? $phone->getId():'') ?>" class="btn btn-default btn-xs phone-edit"
                                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                        <span class="glyphicon glyphicon-edit" ></span>
                                    </button>                                                            
                                    <button value="/contact/delete-phone-form/<?= $phone->getId() ?>" class="btn btn-default btn-xs this-delete"
                                            title="Удалить">
                                        <span class="glyphicon glyphicon-remove" ></span>
                                    </button>                                                            
                                </div>                                        
                           </th>
                       </tr>
                    <?php endforeach; ?>
                </table>
            <?php endforeach; ?>
        </div>
        <div id="section3">
            <h2>Электронная почта</h2>
            <?php foreach ($office->getContacts() as $contact):?>
                <p>
                    <a class="btn btn-default" href="<?= $this->url('contact', 
                                        ['action'=>'email', 'id'=>$contact->getId()]); ?>">
                                    <span class="glyphicon glyphicon-pencil" ></span> <?= (count($contact->getEmails())) ? 'Изменить':'Добавить'; ?>
                    </a>
                </p>
                <table class="table table-striped table-bordered">
                    <?php foreach ($contact->getEmails() as $email): ?>
                        <tr>
                           <th class="email_name"><?= $email->getName() ?></th>
                       </tr>
                    <?php endforeach; ?>
                </table>
            <?php endforeach; ?>
        </div>
        <hr>
        <div id="section4">
            <h2>Мессенджеры</h2>
            <?php foreach ($office->getContacts() as $contact):?>
                <p>
                    <a class="btn btn-default" href="<?= $this->url('contact', 
                                        ['action'=>'messengers', 'id'=>$contact->getId()]); ?>">
                                    <span class="glyphicon glyphicon-pencil" ></span> Изменить
                    </a>
                </p>
                <table class="table table-striped table-bordered">
                    <tr>
                       <td class="">ICQ</td>
                       <th class=""><?= $contact->getIcq() ?></th>
                   </tr>
                    <tr>
                       <td class="">Telegramm</td>
                       <th class=""><?= $contact->getTelegramm() ?></th>
                   </tr>
                </table>
            <?php endforeach; ?>
        </div>
        <div id="section5">
            <h2>Адреса</h2>
            <?php foreach ($office->getContacts() as $contact):?>
                <p>
                    <a class="btn btn-default" href="<?= $this->url('contact', 
                                        ['action'=>'address', 'id'=>$contact->getId()]); ?>">
                                    <span class="glyphicon glyphicon-pencil" ></span> Изменить
                    </a>
                </p>
                <table class="table table-striped table-bordered">
                    <tr>
                       <td class="">Адрес для документов</td>
                       <th class=""><?= $contact->getAddress() ?></th>
                   </tr>
                    <tr>
                       <td class="">Адрес для SMS</td>
                       <th class=""><?= $contact->getAddressSms() ?></th>
                   </tr>
                </table>
            <?php endforeach; ?>
        </div>
        <div id="section6">
            <h2>Юридические лица</h2>
            <?php foreach ($office->getContacts() as $contact):?>
                <p>
                    <a class="btn btn-default" href="<?= $this->url('legals', 
                                        ['action'=>'legal', 'id'=>$contact->getId()]); ?>">
                                    <span class="glyphicon glyphicon-pencil" ></span> <?= (count($contact->getLegals())) ? 'Изменить':'Добавить'; ?>
                    </a>
                </p>
                <table class="table table-striped table-bordered">
                    <?php foreach ($contact->getLegals() as $legal): ?>
                        <tr>
                           <th class=""><?= $legal->getName() ?></th>
                           <th class=""><?= $legal->getInn() ?></th>
                           <th class=""><?= $legal->getKpp() ?></th>
                       </tr>
                       <tr>
                           <td colspan="3">
                               <?= $legal->getAddress() ?>
                           </td>
                       </tr>
                    <?php endforeach; ?>
                </table>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col-sm-3" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active"><a href="#section1">Офис</a></li>
            <li><a href="#section2">Контактные телефоны</a></li>
            <li><a href="#section3">Электронная почта</a></li>
            <li><a href="#section3">Мессенджеры</a></li>
            <li><a href="#section3">Адреса</a></li>
            <li><a href="#section3">Юридические лица</a></li>
        </ul>
    </div>
</div>

<div class="modal fade" id="modal-dialog" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modal-content">
        </div>
    </div>
</div>

<script>
    $('#modal-dialog').on('show.bs.modal', function (e) {        
        var url = e.relatedTarget.value;
        if (url){
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                   $('#modal-content').html(data);
                })
                .fail(function () {
                    alert("Ошибка открытия формы.");
                }); 
        }
    })    
        
    $('.this-delete').on('click', function(e) {
        var url = e.currentTarget.value;
        if (url){
            if (confirm('Удалить запись?')){
                $.ajax({
                    type: 'GET',
                    url: url //'/contact/delete-phone-form/'+phone,
                })
                    .done(function (data) {
                        if (data == 'ok'){
                            window.location.reload();
                        } else {
                            alert("Не удалось удалить!");
                        }    
                    })
                    .fail(function (e) {
                        alert("Не удалось удалить.");

                    });
            }        
        }        
    })    
    
</script>    