<?php
    $this->headTitle('Заявки поставщикам');
    $this->mainMenu()->setActiveItemId('supplier');
    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Заявки поставщикам'=>$this->url('reserve'),
                ]);
?>    

<h1>Заявки поставщикам</h1>
<p>
    <!--
<a class="btn btn-default" href="
    <?= $this->url('reserve', ['action'=>'add']); ?>">
    Новая заявка
</a>
    -->
</p>

<table class="table table-striped">

    <tr>
         <th>ID</th>
         <th>Дата</th>
         <th>Поставщик</th>
         <th>Сумма</th>
         <th>Статус</th>
         <th>Комментарий</th>
         <th>Действие</th>
     </tr>

    <?php foreach ($reserves as $row): ?>

    <tr>
        <td><?= $this->escapeHtml($row->getId()); ?></td>
        <td>
            <?= $this->escapeHtml(date('d-m-Y', strtotime($row->getDateCreated()))); ?>
        </td>
        <td>
            <a href="<?= $this->url('supplier', ['action'=>'view', 'id'=>$row->getSupplier()->getId()]); ?>">
                <?= $this->escapeHtml($row->getSupplier()->getName()); ?>
            </a> 
        </td>
        <td>
           <?= $this->escapeHtml(round($row->getTotal(), 2)); ?>
        </td>
        <td>
           <?= $this->escapeHtml($row->getStatusAsString()); ?>
        </td>
        <td>
           <?= $this->escapeHtml($row->getComment()); ?>
        </td>
        <td>
            <a class="btn btn-info" href="<?= $this->url('reserve', 
                    ['action'=>'view', 'id'=>$row->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Изменить
            </a>
            <a class="btn btn-danger" href="<?= $this->url('reserve',
                    ['action'=>'delete', 'id'=>$row->getId()]); ?>">
                <span class="glyphicon glyphicon-remove"></span> Удалить
            </a>
        </td>    
    </tr>

    <?php endforeach; ?>   

</table>
<?= $this->paginationControl($reserves,
            'Sliding',
            'application/partial/paginator', 
            ['route' => array('route' => 'reserve')]); ?>

