<?php
$this->headTitle('Заявка №'. $reserve->getId() .' от  '.$reserve->getDateCreatedFormat('d.m.Y').' '.$reserve->getSupplier()->getName());

$this->mainMenu()->setActiveItemId('supplier');

$this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Заявки поставщикам'=>$this->url('reserve'),
                'Заявка №'. $reserve->getId() .' от  '.$reserve->getDateCreatedFormat('d.m.Y').' '.$reserve->getSupplier()->getName() => $this->url('reserve', ['action' => 'view', 'id' => $reserve->getId()]),
                ]);
  
?>

<h1>
    <a href="<?= $this->url('supplier', ['action' => 'view', 'id' => $reserve->getSupplier()->getId()])?>">
        <?= $this->escapeHtml($reserve->getSupplier()->getName()); ?>
    </a>
    <br/>
    <?= $this->escapeHtml('Заявка №'.$reserve->getId().' от '. date('d-m-Y H:i:s', strtotime($reserve->getDateCreated()))); ?>    
</h1>

<div class="row">
    <div class="col-sm-9">
        <table class="table table-striped table-bordered">

           <tr>
                <th>ID</th>
                <th>Товар</th>
                <th>Количество</th>
                <th>Цена</th>
                <th>Сумма</th>
            </tr>

            <?php foreach ($bids as $row): ?>

            <tr>
                <td>
                    <?= $this->escapeHtml($row->getId()); ?>
                </td>
                <td>
                    <?= $this->escapeHtml($row->getGood()->getName()); ?>
                </td>
                <td align="right">
                    <?= $this->escapeHtml($row->getNum()); ?>
                </td>
                <td align="right">
                    <?= $this->escapeHtml(number_format($row->getPrice(), 2, ',', ' ')); ?>
                </td>
                <td align="right">
                    <?= $this->escapeHtml(number_format($row->getNum()*$row->getPrice(), 2, ',', ' ')); ?>
                </td>
            </tr>

            <?php endforeach; ?>   
            <tr>
                <th></th>
                <th align="right">
                    Всего:
                </th>
                <th align="right">

                </th>
                <th align="right">

                </th>
                <td align="right">
                    <b>
                        <?= $this->escapeHtml(number_format($reserve->getTotal(), 2, ',', ' ')); ?>
                    </b>
                </td>
            </tr>

        </table>
    </div>
    <div class="col-sm-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="alert alert-info">
                <?= $reserve->getStatusAsString(); ?>
            </div>
            <?php if ($reserve->getSupplier()->getLegalContact()->getActiveLegal()):?>
                <?php if ($requestSetting = $reserve->getSupplier()->getRequestSettingEmail()):?>
                    <?php if ($requestSetting->getEmail()): ?>
                        <div class="alert alert-success">
                            <a href="<?= $this->url('reserve', 
                                    ['action'=>'mail', 'id'=>$reserve->getId()]); ?>">
                                Отправить заявку на <br/>
                                <?= $requestSetting->getEmail(); ?>
                            </a>
                        </div>
                    <?php endif; ?>    
                <?php else: ?>
                    <div class="alert alert-warning">
                        <?php if ($requestSetting): ?>
                            <button value="/supplier/request-setting-form/<?= $reserve->getSupplier()->getId() ?>?requestSetting=<?= $requestSetting->getId() ?>" class="btn btn-default btn-xs"
                                    data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                Уточнить способ отправки заявки
                                <span class="glyphicon glyphicon-edit" ></span>
                            </button>
                        <?php else:?>
                            <button value="/supplier/request-setting-form/<?= $reserve->getSupplier()->getId() ?>" class="btn btn-default btn-xs"
                                    data-toggle="modal" data-target="#modal-dialog" title="Добавить">
                                Добавить способ отправки заявки
                                <span class="glyphicon glyphicon-edit" ></span>
                            </button>
                        <?php endif;?>
                    </div>    
                <?php endif;?>
                <div class="alert alert-success">
                    <a href="<?= $this->url('reserve', 
                            ['action'=>'print', 'id'=>$reserve->getId()]); ?>">
                        Бланк заявки
                    </a>        
                </div>        
            <?php else: ?>
                <div class="alert alert-warning">
                    <a href="<?= $this->url('supplier', 
                            ['action'=>'view', 'id'=>$reserve->getSupplier()->getId()]); ?>">
                        Чтобы получить заявку, заполните <br/>реквизиты юридического лица
                    </a>        
                </div>    
            <?php endif;?>
        </div>            
    </div>
</div>    
