<?php
    $this->headTitle('Обработка заявок');
    $this->mainMenu()->setActiveItemId('supplier');
    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Обработка заявок'=>$this->url('reserve', ['action' => 'work']),
                ]);
    
$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    
    
?>    
<div id="toolbar">
    <div class="form-inline" role="form">
        <div class="form-group">
            <input name="search" style="width: 400px" class="form-control" type="text" placeholder="Поиск">
        </div>
        <button id="ok" type="submit" class="btn btn-default">OK</button>
    </div>
</div>
<table id="table" 
    data-toggle="table" 
    data-url="/reserve/work-content"
    data-side-pagination="server"
    data-pagination="true" 
    data-page-list="[5, 10, 20, 50]"
    data-toolbar="#toolbar"
    data-show-refresh="true"
    data-show-toggle="true"
    data-query-params="queryParams"
    data-response-handler="responseHandler"
    >
    <thead>
        <tr>
             <th data-field="id" data-type="numeric">ID</th>
             <th data-field="name">Наименование</th>
             <th data-field="code">Артикул</th>
             <th data-field="producer">Производитель</th>
             <th data-field="num" data-align='rigth'>Заказать</th>
             <th data-field="reserved" data-formatter="numFormatter" data-align='rigth'>Заказано</th>
             <th data-field="price" data-formatter="priceFormatter" data-align='rigth'>Цена</th>
             <th data-field="supplier">Поставщик</th>
             <th data-field="incart" data-formatter="incartFormatter" data-align='center'>В заявку</th>             
         </tr>                
    </thead>
</table>

<script type="text/javascript">
    var $table = $('#table'),
        $ok = $('#ok');

    $(function () {
        $ok.click(function () {
            $table.bootstrapTable('refresh');
        });
    });
    
    function queryParams() {
        var params = {offset: 0, limit: 10};
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }    
        return params;
    }
    function responseHandler(res) {
        return res;
    }
    
    function incartFormatter(value, row){
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn';
        if (row.incart){
            btn += ' btn-success"';  
        } else {
            btn += ' btn-default"';
        }
        btn += ' aria-label="Left Align"'; 
        btn += ' id="reserve_index_add_work_' + row.id+'"';
        btn += ' onClick="addWork({id:'+row.id+', supplier: '+row.supplier_id+', good: '+row.good_id+', price: '+row.price+', num: '+row.num+'})"';
        if (row.num > row.reserved){
            btn += '>';
        } else {
            btn += ' disabled>';
        }
        btn += '<span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }
    
    function numFormatter(value, row){
       return '<input class="form-control input-sm" id="reserve'+row.id+'" style="width: 100px" min="0" type="number" value="0"/>'; 
    }
    
    function producerFormatter(value, row) {
        return value.name;
    }
    
    function priceFormatter(value, row) {
        return parseFloat(value).toFixed(2);
    }
    
    var addWork = function(data){
        data.reserve = $('#reserve'+data.id).val();
        $.post(
            '/reserve/add-work',
            data,
            addWorkSuccess
        );
    };
    
    function addWorkSuccess(data)
    {
//        if (data.num){  
//            $('#nav_cart_badge').html(data.num);
//        }  
//        if (data.good){
//            $('#reserve_index_add_work_'+data.good).removeClass('btn-default');
//            $('#reserve_index_add_work_'+data.good).addClass('btn-success');
//        }
    }
</script>