<?php
$this->headTitle($client->getName());

$this->mainMenu()->setActiveItemId('client');

$breadcrumbs_items = ['Главная' => $this->url('home')];
if ($this->access('client.any.manage') || $this->access('client.own.manage')){
    $breadcrumbs_items['Покупатели'] = $this->url('client'); 
}
$breadcrumbs_items[$client->getName()] = $this->url('client', ['action'=>'view', 'id'=>$client->getId()]); 

$this->pageBreadcrumbs()->setItems($breadcrumbs_items);

$this->headScript()
            ->appendFile($this->basePath('js/jquery.mask.min.js'))
        
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<div class="row">
    <div class="col-sm-9">
        <div id="section1">
            <h1>
                <?= $this->escapeHtml($client->getName()); ?>    
            </h1>                        

            <table class="table table-striped">
                <tr>
                    <td>
                        <div class="pull-left">
                            <?= $this->escapeHtml($client->getStatusAsString()); ?>
                        </div>                                        
                        <div class="pull-right">
                            <button value="/client/edit-form/<?= $client->getId() ?>" class="btn btn-default btn-xs"
                                    data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                <span class="glyphicon glyphicon-edit" ></span>
                            </button>
                        </div>                                            
                    </td>
                </tr>
            </table>


        </div>
        
        <h3 class="contact-header">Контакты</h3>
        <p>
            <button value="/client/contact-form/<?= $client->getId() ?>" class="btn btn-default btn-xs"
                    data-toggle="modal" data-target="#modal-dialog" title="Добавить контакт">
                <span class="glyphicon glyphicon-plus" ></span>
                Добавить контакт
            </button>                    
        </p>
        <table class="table table-striped">

           <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Описание</th>
                <th>Телефон</th>
                <th>Email</th>
                <th>Доступ</th>
                <th>Действие</th>
            </tr>

            <?php foreach ($client->getOtherContacts() as $contact): ?>

            <tr>
                <td><?= $this->escapeHtml($contact->getId()); ?></td>
                <td>
                        <?= $this->escapeHtml($contact->getName()); ?>
                </td>
                <td>
                        <?= $this->escapeHtml($contact->getDescription()); ?>
                </td>
                <td>
                    <div>
                        <button value="/contact/phone-form/<?= $contact->getId() ?>" class="btn btn-default btn-xs"
                                data-toggle="modal" data-target="#modal-dialog" title="Добавить телефон">
                            <span class="glyphicon glyphicon-plus" ></span>
                        </button>                    
                        
                    </div>
                    <?php foreach($contact->getPhones() as $phone):?>
                        <div>
                            <div class="pull-left">
                                <?= $this->escapeHtml($phone->getName().' '.$phone->getComment()); ?>
                            </div>
                            <div class="pull-right">
                                <button value="/contact/phone-form/<?= $contact->getId() ?>?phone=<?= $phone->getId() ?>" class="btn btn-default  btn-xs"
                                        data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                    <span class="glyphicon glyphicon-edit" ></span>
                                </button>                    
                                <button value="/contact/delete-phone-form/<?= $phone->getId() ?>" class="btn btn-default this-delete  btn-xs" title="Удалить">
                                    <span class="glyphicon glyphicon-remove" ></span>
                                </button>                                            
                            </div>                                                
                        </div>
                    <?php endforeach;?>
                </td>
                <td>
                    <?= $this->escapeHtml($contact->getEmailsAsString()); ?>
                    <div>
                        <button value="/contact/email-form/<?= $contact->getId() ?>" class="btn btn-default btn-xs"
                                data-toggle="modal" data-target="#modal-dialog" title="Добавить email">
                            <span class="glyphicon glyphicon-plus" ></span>
                            Добавить email
                        </button>                    
                        
                    </div>                        
                </td>
                <td>
                        <?= ($contact->getUser() ? 'есть':'нет') ?>
                </td>
                <td>
                    <div class="pull-right">
                        <button value="/client/contact-form/<?= $client->getId() ?>?contact=<?= $contact->getId() ?>" class="btn btn-default  btn-xs"
                                data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                            <span class="glyphicon glyphicon-edit" ></span>
                        </button>                    
                        <button value="/contact/delete-form/<?= $contact->getId() ?>" class="btn btn-default this-delete  btn-xs" title="Удалить">
                            <span class="glyphicon glyphicon-remove" ></span>
                        </button>                                            
                    </div>
                </td>    
            </tr>

            <?php endforeach; ?>   
        </table>    
        <div id="section2">
            <h3>Адреса</h3>
            <p>
                <button value="/contact/address-form/<?= $client->getLegalContact()->getId() ?>" class="btn btn-default btn-xs"
                        data-toggle="modal" data-target="#modal-dialog" title="Добавить адрес">
                    <span class="glyphicon glyphicon-plus" ></span>
                    Добавить адрес
                </button>                    
            </p>            
            <table class="table table-striped table-bordered">
                <?php if (count($client->getLegalContact()->getAddresses())):?>
                    <?php foreach ($client->getLegalContact()->getAddresses() as $address): ?>
                        <tr>
                            <td>
                                <?= $this->escapeHtml($address->getName()); ?>
                            </td>
                            <td>
                                <div class="pull-left">
                                    <?= $this->escapeHtml($address->getAddress()); ?>
                                </div>                                        
                                <div class="pull-right">
                                    <button value="/contact/address-form/<?= $address->getContact()->getId() ?>?address=<?= $address->getId() ?>" class="btn btn-default btn-xs"
                                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                        <span class="glyphicon glyphicon-edit" ></span>
                                    </button>                                                            
                                    <button value="/contact/delete-address-form/<?= $address->getId() ?>" class="btn btn-default btn-xs this-delete"
                                            title="Удалить">
                                        <span class="glyphicon glyphicon-remove" ></span>
                                    </button>                                                            
                                </div>                                        
                            </td>
                       </tr>
                    <?php endforeach; ?>   
                <?php endif;?>       
            </table>
        </div>
        <div id="section3">
            <h3>Юридические лица</h3>
            <?php foreach ($client->getLegalContacts() as $contact):?>
                <p>
                    <a class="btn btn-default btn-xs" href="<?= $this->url('legals', 
                                        ['action'=>'legal', 'id'=>$contact->getId()]); ?>">
                                    <span class="glyphicon glyphicon-piggy-bank" ></span> <?= (count($contact->getLegals())) ? 'Изменить':'Добавить'; ?>
                    </a>
                </p>
                <table class="table table-striped table-bordered">
                    <?php foreach ($contact->getLegals() as $legal): ?>
                        <tr>
                           <th class=""><?= $legal->getName() ?></th>
                           <th class=""><?= $legal->getInn() ?></th>
                           <th class=""><?= $legal->getKpp() ?></th>
                       </tr>
                    <?php endforeach; ?>
                </table>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col-sm-3" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active"><a href="#section1">Контакты</a></li>
            <li><a href="#section2">Адреса</a></li>
            <li><a href="#section3">Юридические лица</a></li>
        </ul>
    </div>
    
</div>

<div class="modal fade" id="modal-dialog" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="modal-content">
        </div>
    </div>
</div>

<script>
    $('#modal-dialog').on('show.bs.modal', function (e) {        
        var url = e.relatedTarget.value;
        if (url){
            $.ajax({
                type: 'GET',
                url: url
            })
                .done(function (data) {
                   $('#modal-content').html(data);
                })
                .fail(function () {
                    alert("Ошибка открытия формы.");
                }); 
        }
    })    
        
    $('.this-delete').on('click', function(e) {
        var url = e.currentTarget.value;
        if (url){
            if (confirm('Удалить запись?')){
                $.ajax({
                    type: 'GET',
                    url: url,
                })
                    .done(function (data) {
                        if (data == 'ok'){
                            window.location.reload();
                        } else {
                            alert("Не удалось удалить!");
                        }    
                    })
                    .fail(function (e) {
                        alert("Не удалось удалить.");

                    });
            }        
        }        
    })    
    
</script>