<?php
$this->headTitle($client->getName());

$this->mainMenu()->setActiveItemId('client');

$breadcrumbs_items = ['Главная' => $this->url('home')];
if ($this->access('client.any.manage') || $this->access('client.own.manage')){
    $breadcrumbs_items['Покупатели'] = $this->url('client'); 
}
$breadcrumbs_items[$client->getName()] = $this->url('client', ['action'=>'view', 'id'=>$client->getId()]); 

$this->pageBreadcrumbs()->setItems($breadcrumbs_items);

$this->headScript()
            ->appendFile($this->basePath('js/jquery.mask.min.js'))
        
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<div class="row">
    <div class="col-sm-9">
        <div class="panel panel-default" id="section1">
            <div class="panel-heading">
                <h2><?= $client->getName() ?></h2>                
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <div class="pull-left">
                    ID: <?= $this->escapeHtml($client->getId()) ?>
                    Статус: <?= $this->escapeHtml($client->getStatusAsString()) ?>
                </div>
                <div class="pull-right">
                    <button value="/client/edit-form/<?= $client->getId() ?>" class="btn btn-default btn-xs"
                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                        <span class="glyphicon glyphicon-edit" ></span>
                    </button>                                                    
                </div>
            </div>
        </div>
        
        <div class="panel panel-default" id="section3">
            <div class="panel-heading">
                <h3 class="panel-title pull-left">Контакты</h3>
                <div class="pull-right">
                    <button value="/client/employee-form/<?= $client->getId() ?>" class="btn btn-default btn-xs"
                            data-toggle="modal" data-target="#modal-dialog" title="Добавить">
                        <span class="glyphicon glyphicon-plus" ></span>
                    </button>                                                                        
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <?php if ($client->getOtherContacts()): ?>                    
                    <div class="panel-group">
                        <?php foreach ($client->getOtherContacts() as $employee):?>
                            <div class="panel panel-info">
                                <div class="panel-body">
                                    <div class="pull-left">
                                        <strong><?= $employee->getName() ?></strong>
                                        <div>
                                            <?= $employee->getDescription() ?>
                                            <!--<span><?= $employee->getStatusAsString() ?></span>-->
                                        </div>                                    
                                    </div>
                                    <div class="pull-right">                                
                                        <button value="/client/employee-form/<?= $client->getId() ?>?employee=<?= $employee->getId() ?>" class="btn btn-default btn-xs"
                                                data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                            <span class="glyphicon glyphicon-edit" ></span>
                                        </button>                                                    
                                        <button value="/client/delete-employee-form/<?= $employee->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                title="Удалить">
                                            <span class="glyphicon glyphicon-remove" ></span>
                                        </button>                                                           
                                    </div>                                                                        
                                </div>
                                <div class="panel panel-default">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="panel-heading">
                                                <div class="pull-left">
                                                    <div class="panel-title">Контактные телефоны</div>
                                                </div>
                                                <div class="pull-right">
                                                    <button value="/contact/phone-form/<?= $employee->getId() ?>" class="btn btn-default btn-xs"
                                                            data-toggle="modal" data-target="#modal-dialog" title="Добавить телефон">
                                                        <span class="glyphicon glyphicon-plus" ></span>
                                                        <span class="glyphicon glyphicon-phone" ></span>
                                                    </button>                                        
                                                </div>
                                                <div class="clearfix"></div>
                                            </div>
                                            <div class="panel-body">
                                                <div class="panel panel-group">
                                                    <?php foreach ($employee->getPhones() as $phone): ?>
                                                        <div class="panel panel-default">
                                                            <div class="panel-body">
                                                                <div class="pull-left">
                                                                    <?= $phone->getName()?> <span><?= $phone->getComment()?></span>
                                                                </div>
                                                                <div class="pull-right">
                                                                    <button value="/contact/phone-form/<?= $employee->getId() ?>?phone=<?= ($phone ? $phone->getId():'') ?>" class="btn btn-default btn-xs phone-edit"
                                                                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                                                        <span class="glyphicon glyphicon-edit" ></span>
                                                                    </button>                                                            
                                                                    <button value="/contact/delete-phone-form/<?= $phone->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                                            title="Удалить">
                                                                        <span class="glyphicon glyphicon-remove" ></span>
                                                                    </button>                                                            
                                                                </div>
                                                            </div>
                                                        </div>    
                                                    <?php endforeach; ?>
                                                </div>                    
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <div class="pull-left">
                                                        <div class="panel-title">Электронная почта</div>
                                                    </div>
                                                    <div class="pull-right">
                                                        <button value="/contact/email-form/<?= $employee->getId() ?>" class="btn btn-default btn-xs"
                                                                data-toggle="modal" data-target="#modal-dialog" title="Добавить email">
                                                            <span class="glyphicon glyphicon-plus" ></span>
                                                        </button>                                        
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>
                                                <div class="panel-body">
                                                    <div class="panel panel-group">
                                                        <?php foreach ($employee->getEmails() as $email): ?>
                                                            <div class="panel panel-default">
                                                                <div class="panel-body">
                                                                    <div class="pull-left">
                                                                        <?= $email->getName()?>
                                                                    </div>
                                                                    <div class="pull-right">
                                                                        <button value="/contact/email-form/<?= $employee->getId() ?>?email=<?= ($email ? $email->getId():'') ?>" class="btn btn-default btn-xs phone-edit"
                                                                                data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                                                            <span class="glyphicon glyphicon-edit" ></span>
                                                                        </button>                                                            
                                                                        <button value="/contact/delete-email-form/<?= $email->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                                                title="Удалить">
                                                                            <span class="glyphicon glyphicon-remove" ></span>
                                                                        </button>                                                            
                                                                    </div>
                                                                </div>
                                                            </div>    
                                                        <?php endforeach; ?>
                                                    </div>                    
                                                </div>
                                            </div>  
                                        </div>
                                    </div>                                    
                                </div>    
                            </div>
                        <?php endforeach; ?>            
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <div class="panel panel-default" id="section4">
            <?php echo $this->partial('/company/legal/partial-view', ['legalContact' => $legalContact]); ?>
        </div>    
    </div>

    <div class="col-sm-3" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active"><a href="#section1">Контакты</a></li>
            <li><a href="#section2">Адреса</a></li>
            <li><a href="#section4">Юридические лица</a></li>
        </ul>
    </div>
    
</div>