<?php
$this->headTitle($supplier->getName());

$this->mainMenu()->setActiveItemId('supplier');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Поставщики'=>$this->url('supplier'),
            $supplier->getName()=>$this->url('supplier', ['action'=>'view', 'id' => $supplier->getId()])
            ]);  

$this->headScript()
            ->appendFile($this->basePath('js/jquery.mask.min.js'));

$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    
        
?>
<div class="row">
    <div class="col-sm-9">
        <div class="panel panel-default" id="section1">
            <div class="panel-heading">
                <h2><?= $supplier->getName() ?></h2>                
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <div class="pull-left">
                    ID: <?= $this->escapeHtml($supplier->getId()) ?>
                    Статус: <?= $this->escapeHtml($supplier->getStatusAsString()) ?>
                </div>
                <div class="pull-right">
                    <button value="/supplier/edit-form/<?= $supplier->getId() ?>" class="btn btn-default btn-xs"
                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                        <span class="glyphicon glyphicon-edit" ></span>
                    </button>                                                    
                </div>
            </div>
        </div>

        <div class="panel panel-default" id="section3">
            <div class="panel-heading">
                <h3 class="panel-title pull-left">Контакты</h3>
                <div class="pull-right">
                    <button value="/supplier/manager-form/<?= $supplier->getId() ?>" class="btn btn-default btn-xs"
                            data-toggle="modal" data-target="#modal-dialog" title="Добавить">
                        <span class="glyphicon glyphicon-plus" ></span>
                    </button>                                                                        
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <?php if ($supplier->getOtherContacts()): ?>                    
                    <div class="panel-group">
                        <?php foreach ($supplier->getOtherContacts() as $manager):?>
                            <div class="panel panel-info">
                                <div class="panel-body">
                                    <div class="pull-left">
                                        <strong><?= $manager->getName() ?></strong>
                                        <div>
                                            <?= $manager->getDescription() ?>
                                            <!--<span><?= $manager->getStatusAsString() ?></span>-->
                                        </div>                                    
                                    </div>
                                    <div class="pull-right">                                
                                        <button value="/supplier/manager-form/<?= $supplier->getId() ?>?manager=<?= $manager->getId() ?>" class="btn btn-default btn-xs"
                                                data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                            <span class="glyphicon glyphicon-edit" ></span>
                                        </button>                                                    
                                        <button value="/supplier/delete-manager-form/<?= $manager->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                title="Удалить">
                                            <span class="glyphicon glyphicon-remove" ></span>
                                        </button>                                                           
                                    </div>                                                                        
                                </div>
                                <div class="panel panel-default">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="panel-heading">
                                                <div class="pull-left">
                                                    <div class="panel-title">Контактные телефоны</div>
                                                </div>
                                                <div class="pull-right">
                                                    <button value="/contact/phone-form/<?= $manager->getId() ?>" class="btn btn-default btn-xs"
                                                            data-toggle="modal" data-target="#modal-dialog" title="Добавить телефон">
                                                        <span class="glyphicon glyphicon-plus" ></span>
                                                        <span class="glyphicon glyphicon-phone" ></span>
                                                    </button>                                        
                                                </div>
                                                <div class="clearfix"></div>
                                            </div>
                                            <div class="panel-body">
                                                <div class="panel panel-group">
                                                    <?php foreach ($manager->getPhones() as $phone): ?>
                                                        <div class="panel panel-default">
                                                            <div class="panel-body">
                                                                <div class="pull-left">
                                                                    <?= $phone->getName()?> <span><?= $phone->getComment()?></span>
                                                                </div>
                                                                <div class="pull-right">
                                                                    <button value="/contact/phone-form/<?= $manager->getId() ?>?phone=<?= ($phone ? $phone->getId():'') ?>" class="btn btn-default btn-xs phone-edit"
                                                                            data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                                                        <span class="glyphicon glyphicon-edit" ></span>
                                                                    </button>                                                            
                                                                    <button value="/contact/delete-phone-form/<?= $phone->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                                            title="Удалить">
                                                                        <span class="glyphicon glyphicon-remove" ></span>
                                                                    </button>                                                            
                                                                </div>
                                                            </div>
                                                        </div>    
                                                    <?php endforeach; ?>
                                                </div>                    
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <div class="pull-left">
                                                        <div class="panel-title">Электронная почта</div>
                                                    </div>
                                                    <div class="pull-right">
                                                        <button value="/contact/email-form/<?= $manager->getId() ?>" class="btn btn-default btn-xs"
                                                                data-toggle="modal" data-target="#modal-dialog" title="Добавить email">
                                                            <span class="glyphicon glyphicon-plus" ></span>
                                                        </button>                                        
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>
                                                <div class="panel-body">
                                                    <div class="panel panel-group">
                                                        <?php foreach ($manager->getEmails() as $email): ?>
                                                            <div class="panel panel-default">
                                                                <div class="panel-body">
                                                                    <div class="pull-left">
                                                                        <?= $email->getName()?>
                                                                    </div>
                                                                    <div class="pull-right">
                                                                        <button value="/contact/email-form/<?= $manager->getId() ?>?email=<?= ($email ? $email->getId():'') ?>" class="btn btn-default btn-xs phone-edit"
                                                                                data-toggle="modal" data-target="#modal-dialog" title="Изменить">
                                                                            <span class="glyphicon glyphicon-edit" ></span>
                                                                        </button>                                                            
                                                                        <button value="/contact/delete-email-form/<?= $email->getId() ?>" class="btn btn-default btn-xs this-delete"
                                                                                title="Удалить">
                                                                            <span class="glyphicon glyphicon-remove" ></span>
                                                                        </button>                                                            
                                                                    </div>
                                                                </div>
                                                            </div>    
                                                        <?php endforeach; ?>
                                                    </div>                    
                                                </div>
                                            </div>  
                                        </div>
                                    </div>                                    
                                </div>    
                            </div>
                        <?php endforeach; ?>            
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <div class="panel panel-default" id="section4">
            <?php echo $this->partial('/company/legal/partial-view', ['legalContact' => $legalContact]); ?>
        </div>    
        
        <div class="panel panel-default" id="section5">
            <div class="panel-heading">
                Заявки
            </div>
            <div class="panel-body">
                <table id="table" 
                    data-toggle="table" 
                    data-url="/reserve/content?supplier=<?= $supplier->getId(); ?>"
                    data-side-pagination="server"
                    data-pagination="true" 
                    data-page-list="[5, 10, 20, 50]"
                    data-toolbar="#toolbar"
                    data-show-refresh="true"
                    data-show-toggle="true"
                    data-query-params="queryParams"
                    data-response-handler="responseHandler"
                    >
                    <thead>
                        <tr>
                             <th data-field="id" data-type="numeric">ID</th>
                             <th data-field="dateCreated">Дата</th>
                             <th data-field="total">Сумма</th>
                             <th data-field="status">Статус</th>
                             <th data-field="comment">Комментарий</th>
                         </tr>                
                    </thead>
                </table>                
            </div>
        </div>
        
        <div class="panel panel-default" id="section6">
            <div class="panel-heading">
                Загруженные прайсы
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <table class="table table-striped">
                    <?php foreach($raws as $raw):?>
                       <tr>
                            <td>
                                <a href="<?= $this->url('raw', ['action'=>'view', 'id'=>$raw->getId()]); ?>">            
                                    <?= $this->escapeHtml($raw->getBasename()); ?>
                                </a>    
                            </td>
                            <td><?= $this->escapeHtml($raw->getRows()); ?></td>
                            <td><?= $this->escapeHtml($raw->getStatusAsString()); ?></td>
                            <td><?= $this->escapeHtml($raw->getDateCreated()); ?></td>
                            <td>
                                <button value="/raw/delete-form/<?= $raw->getId() ?>" class="btn btn-danger btn-xs this-delete"
                                        title="Удалить">
                                    <span class="glyphicon glyphicon-remove" ></span>
                                </button>                                                           
                            </td>    
                       </tr>
                    <?php endforeach;?>
                </table>           
            </div>            
        </div>
        
        <div class="panel panel-default">
            <div class="panel-heading">
                Файлы прайсов в архивной папке
                <div class="clearfix"></div>
            </div>
            <?php foreach($arxPrice as $filename => $value):?>
                <div class="panel-body">
                    <div class="pull-left">
                        <i><?= date('d-m-Y H:i:s', $value['date'])?></i> (<?= $value['size'] ?>) <?= $filename ?>
                    </div>
                    <div class="pull-right">       
                        <button value="/raw/upload-raw-form/<?= $supplier->getId() ?>?filename=<?= $value['path']?>" class="btn btn-default btn-xs refresh-button"
                                title="Загрузить файл в базу">
                            <span class="glyphicon glyphicon-import" ></span>
                        </button>                                                           
                        <button value="/price/upload-price-file-to-apl-form/<?= $supplier->getId() ?>?filename=<?= $value['path']?>" class="btn btn-default btn-xs refresh-button"
                                title="Закачать прайс на сервер АПЛ">
                            <span class="glyphicon glyphicon-upload" ></span>
                        </button>                                                           
                        <a class="btn btn-default btn-xs" title="Скачать" href="<?= $this->url('price',
                                ['action'=>'download-price-file-form'], ['query' => ['filename' => $value['path']]]); ?>">
                            <span class="glyphicon glyphicon-download"></span>
                        </a>
                        <button value="/price/delete-price-file-form?filename=<?= $value['path']?>" class="btn btn-default btn-xs this-delete"
                                title="Удалить">
                            <span class="glyphicon glyphicon-remove" ></span>
                        </button>                                                           
                    </div>                                                                        
                </div>    
            <? endforeach;?>
        </div>
    </div>
    <div class="col-sm-3" id="side-nav" >
        <ul class="nav nav-stacked nav-list affix">
            <li class="active"><a href="#section1">Контакты</a></li>
            <li><a href="#section2">Адреса</a></li>
            <li><a href="#section3">Юридические лица</a></li>
            <li><a href="#section5">Заявки</a></li>
        </ul>
    </div>
</div>    