<?php
$this->headTitle('Строка '.$rawprice->getId().' '.$rawprice->getRaw()->getSupplier()->getName().' прайс '. $rawprice->getRaw()->getFilename());

$this->mainMenu()->setActiveItemId('raw');

$breadcrumbs_items = [
        'Главная' => $this->url('home'),
        'Прайсы' => $this->url('raw'),
        $rawprice->getRaw()->getSupplier()->getName() => $this->url('supplier', ['action' => 'view', 'id' => $rawprice->getRaw()->getSupplier()->getId()]),        
        $rawprice->getRaw()->getFilename() => $this->url('raw', ['action' => 'view', 'id' => $rawprice->getRaw()->getId()]),
        'Строка '.$rawprice->getId() => $this->url('rawprice', ['action' => 'view', 'id' => $rawprice->getId()]),
    ];

$this->pageBreadcrumbs()->setItems($breadcrumbs_items);

?>

<h1>
    <?= $this->escapeHtml('Строка '.$rawprice->getId().' '.$rawprice->getRaw()->getSupplier()->getName().' прайс '. $rawprice->getRaw()->getFilename()); ?>    
</h1>


<h3 class="contact-header">Данные из строки прайса</h3>
<p>
    <?php 
        $rawdates = $rawprice->getRawdataAsArray();
    ?>
    <ol>
        <?php foreach ($rawdates as $rawdata): ?>
            <li>
                <?= $this->escapeHtml($rawdata); ?>
            </li>
        <?php endforeach; ?>    
    </ol>
</p>

<a class="btn btn-default" href="
    <?= $this->url('rawprice', ['action'=>'parse', 'id' => $rawprice->getId()]); ?>">
    1.Парсить
</a>
<?php if ($rawprice->getProducer()): ?>
    <a class="btn btn-default" href="
        <?= $this->url('rawprice', ['action'=>'unknown-producer', 'id' => $rawprice->getId()]); ?>">
        2.Производитель
    </a>
    <?php if ($rawprice->getUnknownProducer() && $rawprice->getUnknownProducer()->getProducer() && $rawprice->getGoodname()): ?>
        <a class="btn btn-default" href="
            <?= $this->url('rawprice', ['action'=>'good', 'id' => $rawprice->getId()]); ?>">
            3.Товар
        </a>
    <? endif; ?>
    <?php if ($rawprice->getGood()): ?>
        <a class="btn btn-default" href="
            <?= $this->url('rawprice', ['action'=>'price', 'id' => $rawprice->getId()]); ?>">
            4.Цена
        </a>
    <? endif; ?>
<? endif; ?>
<h3 class="contact-header">Прочитанные данные</h3>
<table class="table table-striped">

   <tr>
        <th>Поле</th>
        <th>Значение</th>
    </tr>
    <tr>
        <td>
            Артикул
        </td>
        <td>
            <?= $this->escapeHtml($rawprice->getArticle()) ?>
        </td>
    <tr>
        <td>
            Производитель
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getProducer()) ?>
        </td>
    </tr>    
    <tr>
        <td>
            Страна
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getCountry()) ?>
        </td>
    </tr>    
    <tr>
        <td>
            Наименование
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getGoodname()) ?>
        </td>
    </tr>
    <tr>
        <td>
            Описание
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getDescription()) ?>
        </td>
    </tr>
    <tr>
        <td>
            Картинка
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getImage()) ?>
        </td>
    </tr>
    <tr>
        <td>
            Цена
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getPrice()) ?>
        </td>
    </tr>
    <tr>
        <td>
            Валюта
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getCurrency()) ?>
        </td>
    </tr>
    <tr>
        <td>
            Курс
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getRate()) ?>
        </td>
    </tr>
    <tr>
        <td>
            Остаток
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getRest()) ?>
        </td>
    </tr>
    <tr>
        <td>
            Единица измернеия
        </td>        
        <td>
            <?= $this->escapeHtml($rawprice->getUnit()) ?>
        </td>
    </tr>
</table>
