<?php
    $this->headTitle('Товары');
    $this->mainMenu()->setActiveItemId('rb');
    $this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Справочники'=>$this->url('rb'),
                'Товары'=>$this->url('goods'),
                ]);
    
$this->headLink()
//    ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css')        
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css')        
        ;

$this->headScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-ru-RU.min.js')
            ;    
    
?>    
<h1>Товары</h1>
<div class="row">
    <div class="col-sm-9">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="btn-group">
                    <input type="search" name="search" style="width: 400px" class="form-control" placeholder="Поиск">
                </div>
                <button id="ok" type="submit" class="btn btn-default">OK</button>
            </div>
        </div>
        <table id="table" 
            data-toggle="table" 
            data-url="/shop/shop-content"
            data-side-pagination="server"
            data-pagination="true" 
            data-page-list="[5, 10, 20, 50]"
            data-toolbar="#toolbar"
            data-show-refresh="true"
            data-show-toggle="true"
            data-query-params="queryParams"
            data-response-handler="responseHandler"
            >
            <thead>
                <tr>
                     <th data-field="id" data-type="numeric">ID</th>
                     <th data-field="name">Наименование</th>
                     <th data-field="code">Артикул</th>
                     <th data-field="producer" data-formatter="producerFormatter">Производитель</th>
                     <th data-field="price" data-align="right" data-formatter="priceFormatter" data-sortable="true">Цена</th>
                     <th data-field="num" data-formatter="numFormatter" data-align='rigth'>Количество</th>
                     <th data-field="incart" data-formatter="incartFormatter" data-align='center'>Действие</th>             
                 </tr>                
            </thead>
        </table>
    </div>
    <div class="col-sm-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="panel panel-default">
                <div class="panel-heading">Настройки</div>
                <small>
                    <div class="panel-body">
                        <div>
                            <a href="<?= $this->url('goods', ['action'=>'settings']); ?>" class="alert-link">Значения по умолчанию</a>
                        </div>
                        <div>
                            <a href="<?= $this->url('goods', ['action'=>'add']); ?>" class="alert-link">Добавить новый товар</a>
                        </div>
                        <div>
                            <a href="#" class="alert-link refresh-button" value="/goods/delete-all">Удалить все</a>
                        </div>
                    </div>
                </small>
                
                <div class="panel-heading">Группы</div>
                <small>
                    <div class="panel-body">
                        <?php foreach($groups as $group):?>
                            <div class="text-nowrap text-muted" style="width: 24rem; overflow: hidden; text-overflow:ellipsis">
                                <input type="checkbox" id="p<?= $group->getId() ?>" onchange="refreshTable()" class="group" value="<?= $group->getId() ?>">
                                <label class="font-weight-normal" for="p<?= $group->getId() ?>">
                                    <?= $group->getName() ?>                                                    
                                </label>
                            </div>
                        <?php endforeach ?>                    
                    </div>                    
                </small>
                <div class="panel-heading">Производители</div>
                <small>
                    <div class="panel-body">
                        <?php foreach($producers as $producer):?>
                            <div class="text-nowrap text-muted" style="width: 24rem; overflow: hidden; text-overflow:ellipsis">
                                <input type="checkbox" id="p<?= $producer->getId() ?>" onchange="refreshTable()" class="producer" value="<?= $producer->getId() ?>">
                                <label class="font-weight-normal" for="p<?= $producer->getId() ?>">
                                    <?= $producer->getName() ?>                                                    
                                </label>
                            </div>
                        <?php endforeach ?>                    
                    </div>                    
                </small>
            </div>            
        </div>
    </div>    
</div>    

<script type="text/javascript" async="true">
    function refreshTable(){
        $('#table').bootstrapTable('refresh');
    }

    $('#ok').click(function () {
        refreshTable();
    });
    
    function queryParams() {
        var params = {offset: 0, limit: 10};
        $('#toolbar').find('input[name]').each(function () {
            params[$(this).attr('name')] = $(this).val();
        });
        limit = $('.page-size').html();
        if (limit){
            params.limit = limit;
        }    
        offset = $('li.page-number.active a').html();
        if (offset){
            params.offset = params.limit * (offset - 1);
        }  
        
        var producer = new Array();
        $('.producer:checkbox:checked').each(function () {
            producer.push($(this).val());
        });
        
        if (producer.length){
            params.producer = producer;
        }
        
        var group = new Array();
        $('.group:checkbox:checked').each(function () {
            group.push($(this).val());
        });
        
        if (group.length){
            params.group = group;
        }

        return params;
    }
    
    function responseHandler(res) {
        return res;
    }
    
    function incartFormatter(value, row){
        btn = '<button';
        btn += ' type="button"';
        btn += ' class="btn';
        if (row.incart){
            btn += ' btn-success"';  
        } else {
            btn += ' btn-default"';
        }
        btn += ' aria-label="Left Align"'; 
        btn += ' id="shop_index_add_cart_' + row.id+'"';
        btn += ' onClick="addCart({good: '+row.id+', price: '+row.price+'})"';
        if (row.available && row.price > 0){
            btn += '>';
        } else {
            btn += ' disabled>';
        }
        btn += '<span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>';
        btn += '</button>';
        return btn;
    }
    
    function numFormatter(value, row){
       return '<input class="form-control input-sm" id="num'+row.id+'" style="width: 100px" min="1" type="number" value="1"/>'; 
    }
    
    function producerFormatter(value, row) {
        return value.name;
    }
    
    function priceFormatter(value, row) {
        return parseFloat(value).toFixed(2);
    }
    
    var addCart = function(data){
        data.num = $('#num'+data.good).val();
        $.post(
            '/shop/add-cart',
            data,
            addCartSuccess
        );
    };
    
    function addCartSuccess(data)
    {
        if (data.num){  
            $('#nav_cart_badge').html(data.num);
        }  
        if (data.good){
            $('#shop_index_add_cart_'+data.good).removeClass('btn-default');
            $('#shop_index_add_cart_'+data.good).addClass('btn-success');
        }
    }

    $('.refresh-button').on('click', function(e) {
        var url = e.currentTarget.value;
        
        if (url){
            if (confirm('Подтвердите действие!')){
                var dialog = bootbox.dialog({
                    message: '<p class="text-center"><i class="fa fa-spin fa-spinner"></i>Подождите, пока мы что-нибудь сделаем ...</p>',
                    closeButton: false
                });

                $.ajax({
                    type: 'GET',
                    url: url
                })
                    .done(function (data) {
                        dialog.modal('hide');
                        if (data == 'ok'){
                            bootbox.alert("Данные успешно обновлены.");
                        }    
                    })
                    .fail(function () {
                        dialog.modal('hide');
                        bootbox.alert("Произошла ошибка при выполнении операции.");
                    });
            }        
        }        
    })
</script>

<!--<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Наименование</th>
        <th>Артикул</th>
        <th>Производитель</th>
        <th>Описание</th>
        <th>Налог</th>
        <th>Доступность</th>
        <th>Действие</th>
    </tr>
    
    <?php if (count($goods)): ?>
        <?php foreach ($goods as $row): ?>

        <tr>
            <td><?= $this->escapeHtml($row->getId()); ?></td>
            <td>
                <a href="<?= $this->url('goods', ['action'=>'view', 'id'=>$row->getId()]); ?>">
                    <?= $this->escapeHtml($row->getName()); ?>
                </a> 
            </td>
            <td><?= $this->escapeHtml($row->getCode()); ?></td>        
            <td><?= $this->escapeHtml($row->getProducer()->getName()); ?></td>        
            <td><?= $this->escapeHtml($row->getDescription()); ?></td>        
            <td><?= $this->escapeHtml($row->getTax()->getName()); ?></td>        
            <td><?= $this->escapeHtml($row->getAvailable()); ?></td>        
            <td>
                <a class="btn btn-info" href="<?= $this->url('goods', 
                        ['action'=>'edit', 'id'=>$row->getId()]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span> Изменить
                </a>
                <a class="btn btn-danger" href="<?= $this->url('goods',
                        ['action'=>'delete', 'id'=>$row->getId()]); ?>">
                    <span class="glyphicon glyphicon-remove"></span> Удалить
                </a>
            </td>    
        </tr>

        <?php endforeach; ?>   
    <?php endif;?>
</table>
-->
<script >
</script>