<?php
$this->headTitle('Заказ №'. $order->getId() .' от  '.$order->getDateCreatedFormat('d.m.Y').' '.$order->getClient()->getName());

$this->mainMenu()->setActiveItemId('order');

$this->pageBreadcrumbs()->setItems([
                'Главная'=>$this->url('home'),
                'Заказы'=>$this->url('order'),
                'Заказ №'. $order->getId() .' от  '.$order->getDateCreatedFormat('d.m.Y').' '.$order->getClient()->getName() => $this->url('order', ['action' => 'view', 'id' => $order->getId()]),
                ]);
  
?>

<h1>
    <?= $this->escapeHtml($order->getClient()->getName()); ?>
    <br/>
    <?= $this->escapeHtml('Заказ №'.$order->getId().' от '. date('d-m-Y H:i:s', strtotime($order->getDateCreated()))); ?>    
</h1>

<div class="row">
    <div class="col-sm-9">
        <table class="table table-striped table-bordered">

           <tr>
                <th>ID</th>
                <th>Товар</th>
                <th>Количество</th>
                <th>Цена</th>
                <th>Сумма</th>
            </tr>

            <?php foreach ($bids as $row): ?>

            <tr>
                <td>
                    <?= $this->escapeHtml($row->getId()); ?>
                </td>
                <td>
                    <?= $this->escapeHtml($row->getGood()->getName()); ?>
                </td>
                <td align="right">
                    <?= $this->escapeHtml($row->getNum()); ?>
                    <?php if ($this->access('supplier.manage')):?>
                        <span>/<?= $this->escapeHtml($row->getReserved()); ?></span>
                    <?php endif; ?>
                </td>
                <td align="right">
                    <?= $this->escapeHtml(number_format($row->getPrice(), 2, ',', ' ')); ?>
                </td>
                <td align="right">
                    <?= $this->escapeHtml(number_format($row->getNum()*$row->getPrice(), 2, ',', ' ')); ?>
                </td>
            </tr>

            <?php endforeach; ?>   
            <tr>
                <th></th>
                <th align="right">
                    Всего:
                </th>
                <th align="right">

                </th>
                <th align="right">

                </th>
                <td align="right">
                    <b>
                        <?= $this->escapeHtml(number_format($order->getTotal(), 2, ',', ' ')); ?>
                    </b>
                </td>
            </tr>

        </table>
    </div>    
    <div class="col-sm-3" id="side-nav" >
        <div class="nav nav-stacked nav-list affix">
            <div class="alert alert-warning">
                <?php if ($order->getClient()->getLegalContact()->getActiveLegal()):?>
                        <a href="<?= $this->url('order', 
                                ['action'=>'print', 'id'=>$order->getId()]); ?>">
                            Счет на оплату
                        </a>        
                <?php else: ?>
                    <a href="<?= $this->url('legals', 
                            ['action'=>'legal', 'id'=>$order->getClient()->getLegalContact()->getId()]); ?>">
                        Чтобы получить счет, заполните <br/>реквизиты юридического лица
                    </a>        
                <?php endif;?>
            </div>    
            <?php if ($order->getReservedStatus() < 100): ?>
                <div class="alert alert-info">
                    <a href="<?= $this->url('reserve', 
                            ['action'=>'checkout', 'id'=>$order->getId()]); ?>">
                        Заказать у поставщиков
                    </a>
                </div>                
            <?php endif;?>
            <?php if ($order->getReservedStatus() > 0): ?>
                <div class="alert alert-success">
                    Заказано у поставщиков на <?= $order->getReservedStatus(); ?>%.
                    <br/>
                    <a href="<?= $this->url('order', 
                            ['action'=>'check-reserved', 'id'=>$order->getId()]); ?>">
                        Проверить
                    </a>
                </div>
            <?php endif;?>
        </div>            
    </div>
</div>

